# Generated by Django 4.1.5 on 2023-02-20 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cheese', models.CharField(blank=True, default='Empty', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Crust',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crust', models.CharField(blank=True, default='Empty', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sauces',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sauces', models.CharField(blank=True, default='Empty', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(blank=True, default='Empty', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('toppings', models.CharField(blank=True, default='Empty', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cheese', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PizzaApp.cheese')),
                ('crust', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PizzaApp.crust')),
                ('sauces', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PizzaApp.sauces')),
                ('size', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PizzaApp.size')),
                ('toppings', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PizzaApp.toppings')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=16)),
                ('date', models.DateField()),
                ('card_cvv', models.CharField(max_length=3)),
                ('address', models.CharField(max_length=100)),
                ('pizza_details', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PizzaApp.pizza')),
            ],
        ),
    ]
