# Generated by Django 4.1.5 on 2023-02-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheese',
            name='cheese',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='crust',
            name='crust',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sauces',
            name='sauces',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='toppings',
            name='toppings',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
