# Generated by Django 4.1.5 on 2023-02-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0002_alter_cheese_cheese_alter_crust_crust_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
