# Generated by Django 4.1.5 on 2023-02-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0003_pizza_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='name',
        ),
    ]
