# Generated by Django 4.1.5 on 2023-02-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0004_remove_pizza_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='date',
            field=models.CharField(max_length=5),
        ),
    ]
