# Generated by Django 4.1.5 on 2023-02-28 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0011_remove_pizza_toppings_pizza_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='pizza_details',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='PizzaApp.pizza'),
        ),
    ]
